# This is where you can add your custom levels!
# Make sure not to skip numbers, otherwise the plugin will break.
# Remove 'none' to add your custom levels. The last number in the list will be the highest level that you can obtain.
# Format: "1 150" 1 is the next level, 150 is the amount of xp you need to gain to get to that level.

levels:
    - none